version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes: # Bind mounts to avoid rebuilding the image every time the code changes
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://127.0.0.1:8000
    depends_on:
      - backend
    
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - FLASK_ENV=${FLASK_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:13
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: